GEMINI_API_KEY = "AIzaSyA1WkybbDYOSktxmUu3x8Be_cjGnjMTbFs"
SERPER_API_KEY = "fb11fa924820ec0982f5118ef0cc6a8809b80964"
PINECONE_API_KEY = "pcsk_22597x_NH2uDbw3R8bgndiWyRJcjpWirjwdcZaG99FTHLwPLH7yQnoAQ9Gd3EfWicAUWaF"